/**
 * sdk_config.h - SP-1 Bridge Firmware Configuration
 */

#ifndef SDK_CONFIG_H
#define SDK_CONFIG_H

/* ── Clock ─────────────────────────────────────────────────────── */
#define NRFX_CLOCK_ENABLED 1
#define NRFX_CLOCK_CONFIG_LF_SRC 1
#define NRFX_CLOCK_CONFIG_IRQ_PRIORITY 6
#define NRF_CLOCK_ENABLED 1

/* ── Power ─────────────────────────────────────────────────────── */
#define NRFX_POWER_ENABLED 1
#define NRFX_POWER_CONFIG_IRQ_PRIORITY 6
#define NRF_POWER_ENABLED 1
#define POWER_ENABLED 1
#define NRFX_POWER_CONFIG_DEFAULT_DCDCEN 0
#define NRFX_POWER_CONFIG_DEFAULT_DCDCENHV 0

/* ── USBD ──────────────────────────────────────────────────────── */
#define NRFX_USBD_ENABLED 1
#define NRFX_USBD_CONFIG_IRQ_PRIORITY 6
#define NRFX_USBD_CONFIG_DMASCHEDULER_MODE 0
#define NRFX_USBD_CONFIG_DMASCHEDULER_ISO_BOOST 1
#define USBD_ENABLED 1
#define USBD_CONFIG_IRQ_PRIORITY 6
#define POWER_CONFIG_IRQ_PRIORITY 6

#define APP_USBD_ENABLED 1
#define APP_USBD_VID 0x2367
#define APP_USBD_PID 0x1701
#define APP_USBD_DEVICE_VER_MAJOR 1
#define APP_USBD_DEVICE_VER_MINOR 0
#define APP_USBD_DEVICE_VER_SUB 0
#define APP_USBD_STRING_ID_CONFIGURATION 4
#define APP_USBD_STRING_CONFIGURATION "SP1Bridge"
#define APP_USBD_CONFIG_SELF_POWERED 1
#define APP_USBD_CONFIG_MAX_POWER 100
#define APP_USBD_CONFIG_POWER_EVENTS_PROCESS 1
#define APP_USBD_CONFIG_EVENT_QUEUE_ENABLE 1
#define APP_USBD_CONFIG_EVENT_QUEUE_SIZE 32
#define APP_USBD_CONFIG_SOF_HANDLING_MODE 1
#define APP_USBD_CONFIG_SOF_TIMESTAMP_PROVIDE 0
#define APP_USBD_CONFIG_DESC_STRING_SIZE 31
#define APP_USBD_CONFIG_DESC_STRING_UTF_ENABLED 0
#define APP_USBD_STRINGS_LANGIDS APP_USBD_LANG(APP_USBD_LANG_AND_SUBLANG(APP_USBD_LANG_ENGLISH, APP_USBD_SUBLANG_ENGLISH_US))
#define APP_USBD_STRING_ID_MANUFACTURER 1
#define APP_USBD_STRING_ID_PRODUCT 2
#define APP_USBD_STRING_ID_SERIAL 3
#define APP_USBD_STRINGS_MANUFACTURER APP_USBD_STRING_DESC("Kano Computing")
#define APP_USBD_STRINGS_PRODUCT APP_USBD_STRING_DESC("SP-1 Bridge")
#define APP_USBD_STRING_SERIAL APP_USBD_STRING_DESC("000000000000")
#define APP_USBD_STRINGS_CONFIGURATION APP_USBD_STRING_DESC("SP1Bridge")
#define APP_USBD_STRINGS_USER
#define APP_USBD_CONFIG_LOG_ENABLED 0

/* CDC ACM */
#define APP_USBD_CDC_ACM_ENABLED 1
#define APP_USBD_CDC_ACM_CONFIG_LOG_ENABLED 0
#define APP_USBD_CDC_ACM_ZLP_ON_EPSIZE_WRITE 1

/* ── Logging ───────────────────────────────────────────────────── */
#define NRF_LOG_ENABLED 0
#define NRF_LOG_DEFAULT_LEVEL 0
#define NRF_LOG_BACKEND_RTT_ENABLED 0
#define NRF_LOG_BACKEND_UART_ENABLED 0
#define NRF_LOG_BACKEND_SERIAL_USES_UART 0
#define NRF_LOG_STR_FORMATTER_TIMESTAMP_FORMAT_ENABLED 0
#define NRF_LOG_USES_TIMESTAMP 0

/* ── Misc Libraries ────────────────────────────────────────────── */
#define NRF_FPRINTF_ENABLED 1
#define NRF_STRERROR_ENABLED 1
#define NRF_BALLOC_ENABLED 1
#define NRF_BALLOC_CONFIG_DEBUG_ENABLED 0
#define NRF_MEMOBJ_ENABLED 1
#define NRF_ATFIFO_ENABLED 1
#define NRF_SORTLIST_ENABLED 1
#define NRF_QUEUE_ENABLED 1
#define NRF_SECTION_ITER_ENABLED 1
#define NRF_PWR_MGMT_ENABLED 1
#define NRF_PWR_MGMT_CONFIG_AUTO_SHUTDOWN_RETRY 0
#define NRF_PWR_MGMT_CONFIG_USE_SCHEDULER 0
#define NRF_PWR_MGMT_CONFIG_HANDLER_PRIORITY_COUNT 3

/* ── Systick ───────────────────────────────────────────────────── */
#define NRFX_SYSTICK_ENABLED 1

/* ── App Timer ─────────────────────────────────────────────────── */
#define APP_TIMER_ENABLED 1
#define APP_TIMER_V2 1
#define APP_TIMER_V2_RTC1_ENABLED 1
#define APP_TIMER_CONFIG_RTC_FREQUENCY 0
#define APP_TIMER_CONFIG_IRQ_PRIORITY 6

/* ── Hardfault ─────────────────────────────────────────────────── */
#define HARDFAULT_HANDLER_ENABLED 1

/* ── Segger RTT ────────────────────────────────────────────────── */
#define SEGGER_RTT_CONFIG_MAX_NUM_UP_BUFFERS 2
#define SEGGER_RTT_CONFIG_MAX_NUM_DOWN_BUFFERS 2
#define SEGGER_RTT_CONFIG_BUFFER_SIZE_UP 512
#define SEGGER_RTT_CONFIG_BUFFER_SIZE_DOWN 16
#define SEGGER_RTT_CONFIG_DEFAULT_MODE 0

#endif /* SDK_CONFIG_H */
